export const authStatus={
	LOGIN_REQUEST:"LOGIN_REQUEST",
	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	LOGIN_FAILED:"LOGIN_FAILED",
	LOGOUT_SUCCESS:"LOGOUT_SUCCESS"
}

 export const syncStatus={
 	SYNC_DESCRIPTION_REQUEST:"SYNC_DESCRIPTION_REQUEST",
 	SYNC_DESCRIPTION_SUCCESS:"SYNC_DESCRIPTION_SUCCESS",
 	SYNC_DESCRIPTION_FAILED:"SYNC_DESCRIPTION_FAILED",
 	SYNC_STOCK_REQUEST:"SYNC_STOCK_REQUEST",
 	SYNC_STOCK_SUCCESS:"SYNC_STOCK_SUCCESS",
 	SYNC_STOCK_FAILED:"SYNC_STOCK_FAILED"
 }

 export const categoryStatus={
 	CATEGORY_ADD_REQUEST:"CATEGORY_ADD_REQUEST",
 	CATEGORY_ADD_SUCCESS:"CATEGORY_ADD_SUCCESS",
 	CATEGORY_ADD_FAILED:"CATEGORY_ADD_FAILED",
 	CATEGORY_GET_REQUEST:"CATEGORY_GET_REQUEST",
 	CATEGORY_GET_SUCCESS:"CATEGORY_GET_SUCCESS",
 	CATEGORY_GET_FAILED:"CATEGORY_GET_FAILED",
 	CATEGORY_DELETE_REQUEST:"CATEGORY_DELETE_REQUEST",
 	CATEGORY_DELETE_SUCCESS:"CATEGORY_DELETE_SUCCESS",
 	CATEGORY_DELETE_FAILED:"CATEGORY_DELETE_FAILED"
 }

 export const cmsStatus={
 	CMS_REQUEST:"CMS_ADD_REQUEST",
 	CMS_SUCCESS:"CMS_ADD_SUCCESS",
 	CMS_FAILED:"CMS_ADD_FAILED",
 	CMS_GET_REQUEST:"CMS_GET_REQUEST",
 	CMS_GET_SUCCESS:"CMS_GET_SUCCESS",
 	CMS_GET_FAILED:"CMS_GET_FAILED",
 	CMS_DELETE_REQUEST:"CMS_DELETE_REQUEST",
 	CMS_DELETE_SUCCESS:"CMS_DELETE_SUCCESS",
 	CMS_DELETE_FAILED: "CMS_DELETE_FAILED",
 	CMS_UPDATE_REQUEST:"CMS_UPDATE_REQUEST",
 	CMS_UPDATE_SUCCESS:"CMS_UPDATE_SUCCESS",
 	CMS_UPDATE_FAILED: "CMS_UPDATE_FAILED",
 	COUPON_REQUEST:"COUPON_REQUEST",
 	COUPON_EXIST:"COUPON_EXIST",
 	COUPON_SUCCESS:"COUPON_SUCCESS",
 	COUPON_FAILED: "COUPON_FAILED",
 	COUPON_GET_REQUEST:"COUPON_GET_REQUEST",
 	COUPON_GET_SUCCESS:"COUPON_GET_SUCCESS",
 	COUPON_GET_FAILED:"COUPON_GET_FAILED",
 	COUPON_UPDATE_REQUEST:"COUPON_UPDATE_REQUEST",
	COUPON_UPDATE_SUCCESS:"COUPON_UPDATE_SUCCESS",
	COUPON_UPDATE_FAILED:"COUPON_UPDATE_FAILED",
 	COUPON_DELETE_REQUEST:"COUPON_DELETE_REQUEST",
	COUPON_DELETE_SUCCESS:"COUPON_DELETE_SUCCESS",
	COUPON_DELETE_FAILED:"COUPON_DELETE_FAILED"
 }

 export const vitalStatus={
	VITAL_GET_SUCCESS:"VITAL_GET_SUCCESS",
	VITAL_GET_FAILED:"VITAL_GET_FAILED",
	VITAL_GET_REQUEST:"VITAL_GET_REQUEST",
	VITAL_REQUEST:"VITAL_REQUEST",
	VITAL_EXIST:"VITAL_EXIST",
	VITAL_SUCCESS:"VITAL_SUCCESS",
	VITAL_FAILED: "VITAL_FAILED",
	VITAL_DELETE_REQUEST:"VITAL_DELETE_REQUEST",
 	VITAL_DELETE_SUCCESS:"VITAL_DELETE_SUCCESS",
 	VITAL_DELETE_FAILED: "VITAL_DELETE_FAILED",
 	VITAL_UPDATE_REQUEST:"VITAL_UPDATE_REQUEST",
 	VITAL_UPDATE_SUCCESS:"VITAL_UPDATE_SUCCESS",
 	VITAL_UPDATE_FAILED: "VITAL_UPDATE_FAILED",
}

export const diseaseStatus={
	DISEASE_GET_SUCCESS:"DISEASE_GET_SUCCESS",
	DISEASE_GET_FAILED:"DISEASE_GET_FAILED",
	DISEASE_GET_REQUEST:"DISEASE_GET_REQUEST",
	DISEASE_REQUEST:"DISEASE_REQUEST",
	DISEASE_EXIST:"DISEASE_EXIST",
	DISEASE_SUCCESS:"DISEASE_SUCCESS",
	DISEASE_FAILED: "DISEASE_FAILED",
	DISEASE_DELETE_REQUEST:"DISEASE_DELETE_REQUEST",
 	DISEASE_DELETE_SUCCESS:"DISEASE_DELETE_SUCCESS",
 	DISEASE_DELETE_FAILED: "DISEASE_DELETE_FAILED",
 	DISEASE_UPDATE_REQUEST:"DISEASE_UPDATE_REQUEST",
 	DISEASE_UPDATE_SUCCESS:"DISEASE_UPDATE_SUCCESS",
 	DISEASE_UPDATE_FAILED: "DISEASE_UPDATE_FAILED",
}

export const medicineStatus={
	MEDICINE_GET_SUCCESS:"MEDICINE_GET_SUCCESS",
	MEDICINE_GET_FAILED:"MEDICINE_GET_FAILED",
	MEDICINE_GET_REQUEST:"MEDICINE_GET_REQUEST",
	MEDICINE_REQUEST:"MEDICINE_REQUEST",
	MEDICINE_EXIST:"MEDICINE_EXIST",
	MEDICINE_SUCCESS:"MEDICINE_SUCCESS",
	MEDICINE_FAILED: "MEDICINE_FAILED",
	MEDICINE_DELETE_REQUEST:"MEDICINE_DELETE_REQUEST",
 	MEDICINE_DELETE_SUCCESS:"MEDICINE_DELETE_SUCCESS",
 	MEDICINE_DELETE_FAILED: "MEDICINE_DELETE_FAILED",
 	MEDICINE_UPDATE_REQUEST:"MEDICINE_UPDATE_REQUEST",
 	MEDICINE_UPDATE_SUCCESS:"MEDICINE_UPDATE_SUCCESS",
 	MEDICINE_UPDATE_FAILED: "MEDICINE_UPDATE_FAILED",
}

export const adminStatus = {
	ADMIN_PROFILE_UPDATE_REQUEST:"ADMIN_PROFILE_UPDATE_REQUEST",
 	ADMIN_PROFILE_UPDATE_SUCCESS:"ADMIN_PROFILE_UPDATE_SUCCESS",
 	ADMIN_PROFILE_UPDATE_FAILED: "ADMIN_PROFILE_UPDATE_FAILED",
	ADMIN_PROFILE_GET_SUCCESS:"ADMIN_PROFILE_GET_SUCCESS",
	ADMIN_PROFILE_GET_FAILED:"ADMIN_PROFILE_GET_FAILED",
	ADMIN_PROFILE_GET_REQUEST:"ADMIN_PROFILE_GET_REQUEST",
}